import type { UiLabEntry } from '@/features/ui-lab/types';
import {
  BadgeHarness,
  ButtonHarness,
  CardHarness,
  CheckboxHarness,
  InputHarness,
  PopoverHarness,
  SelectHarness,
  SliderHarness,
  SpinnerHarness,
  TableHarness,
  TabsHarness,
  TooltipContentHarness,
  TooltipHarness,
} from '@/features/ui-lab/harnesses/primitives-harnesses';

export const primitiveEntries: UiLabEntry[] = [
  {
    id: 'button',
    title: 'Button',
    category: 'ui-primitives',
    dataMode: 'fixture',
    description: 'Primary, surface, default, and ghost variants.',
    render: () => <ButtonHarness />,
  },
  {
    id: 'card',
    title: 'Card',
    category: 'ui-primitives',
    dataMode: 'fixture',
    description: 'Card container and header/body/footer spacing.',
    render: () => <CardHarness />,
  },
  {
    id: 'tooltip',
    title: 'Tooltip',
    category: 'ui-primitives',
    dataMode: 'fixture',
    description: 'Tooltip content and trigger wrapping behavior.',
    render: () => <TooltipHarness />,
  },
  {
    id: 'tooltip-content',
    title: 'Tooltip Content',
    category: 'ui-primitives',
    dataMode: 'fixture',
    description: 'Shared tooltip content layouts from src/components/shared/tooltip-content.tsx.',
    render: () => <TooltipContentHarness />,
  },
  {
    id: 'input',
    title: 'Input',
    category: 'ui-primitives',
    dataMode: 'fixture',
    description: 'Input field states, labels, and error styling.',
    render: () => <InputHarness />,
  },
  {
    id: 'select',
    title: 'Select',
    category: 'ui-primitives',
    dataMode: 'fixture',
    description: 'Radix select trigger and dropdown content.',
    render: () => <SelectHarness />,
  },
  {
    id: 'badge',
    title: 'Badge',
    category: 'ui-primitives',
    dataMode: 'fixture',
    description: 'Badge variants and compact spacing checks.',
    render: () => <BadgeHarness />,
  },
  {
    id: 'table',
    title: 'Table',
    category: 'ui-primitives',
    dataMode: 'fixture',
    description: 'Table alignment and compact body styles.',
    render: () => <TableHarness />,
  },
  {
    id: 'tabs',
    title: 'Tabs',
    category: 'ui-primitives',
    dataMode: 'fixture',
    description: 'Tab list and active indicator treatment.',
    render: () => <TabsHarness />,
  },
  {
    id: 'slider',
    title: 'Slider',
    category: 'ui-primitives',
    dataMode: 'fixture',
    description: 'Slider track/thumb visuals and value binding.',
    render: () => <SliderHarness />,
  },
  {
    id: 'checkbox',
    title: 'Checkbox',
    category: 'ui-primitives',
    dataMode: 'fixture',
    description: 'Default and highlighted checkbox variants.',
    render: () => <CheckboxHarness />,
  },
  {
    id: 'popover',
    title: 'Popover',
    category: 'ui-primitives',
    dataMode: 'fixture',
    description: 'Popover overlay spacing and border treatment.',
    render: () => <PopoverHarness />,
  },
  {
    id: 'spinner',
    title: 'Spinner',
    category: 'ui-primitives',
    dataMode: 'fixture',
    description: 'Spinner sizes and animation behavior.',
    render: () => <SpinnerHarness />,
  },
];
