import type { UiLabEntry } from '@/features/ui-lab/types';
import { BorrowModalHarness } from '@/features/ui-lab/harnesses/borrow-modal-harness';
import {
  AssetFilterHarness,
  MarketDetailsBlockHarness,
  MarketIdentityHarness,
  MarketSelectionModalHarness,
  MarketSelectorHarness,
  NetworkFilterHarness,
} from '@/features/ui-lab/harnesses/market-harnesses';
import {
  BadgeHarness,
  ButtonHarness,
  CardHarness,
  CheckboxHarness,
  InputHarness,
  PopoverHarness,
  SelectHarness,
  SliderHarness,
  SpinnerHarness,
  TableHarness,
  TabsHarness,
  TooltipContentHarness,
  TooltipHarness,
} from '@/features/ui-lab/harnesses/primitives-harnesses';
import {
  AccountIdentityHarness,
  CollateralIconsDisplayHarness,
  DropdownMenuHarness,
  IconSwitchHarness,
  RefetchIconHarness,
  SectionTagHarness,
  TableContainerWithHeaderHarness,
  TablePaginationHarness,
  ToastHarness,
  TransactionIdentityHarness,
} from '@/features/ui-lab/harnesses/shared-harnesses';
import { SupplyModalHarness } from '@/features/ui-lab/harnesses/supply-modal-harness';

export const uiLabRegistry: UiLabEntry[] = [
  {
    id: 'button',
    title: 'Button',
    category: 'ui-primitives',
    description: 'Primary, surface, default, and ghost variants.',
    render: () => <ButtonHarness />,
  },
  {
    id: 'card',
    title: 'Card',
    category: 'ui-primitives',
    description: 'Card container and header/body/footer spacing.',
    render: () => <CardHarness />,
  },
  {
    id: 'tooltip',
    title: 'Tooltip',
    category: 'ui-primitives',
    description: 'Tooltip content and trigger wrapping behavior.',
    render: () => <TooltipHarness />,
  },
  {
    id: 'tooltip-content',
    title: 'Tooltip Content',
    category: 'ui-primitives',
    description: 'Shared tooltip content layouts from src/components/shared/tooltip-content.tsx.',
    render: () => <TooltipContentHarness />,
  },
  {
    id: 'input',
    title: 'Input',
    category: 'ui-primitives',
    description: 'Input field states, labels, and error styling.',
    render: () => <InputHarness />,
  },
  {
    id: 'select',
    title: 'Select',
    category: 'ui-primitives',
    description: 'Radix select trigger and dropdown content.',
    render: () => <SelectHarness />,
  },
  {
    id: 'badge',
    title: 'Badge',
    category: 'ui-primitives',
    description: 'Badge variants and compact spacing checks.',
    render: () => <BadgeHarness />,
  },
  {
    id: 'table',
    title: 'Table',
    category: 'ui-primitives',
    description: 'Table alignment and compact body styles.',
    render: () => <TableHarness />,
  },
  {
    id: 'tabs',
    title: 'Tabs',
    category: 'ui-primitives',
    description: 'Tab list and active indicator treatment.',
    render: () => <TabsHarness />,
  },
  {
    id: 'slider',
    title: 'Slider',
    category: 'ui-primitives',
    description: 'Slider track/thumb visuals and value binding.',
    render: () => <SliderHarness />,
  },
  {
    id: 'checkbox',
    title: 'Checkbox',
    category: 'ui-primitives',
    description: 'Default and highlighted checkbox variants.',
    render: () => <CheckboxHarness />,
  },
  {
    id: 'popover',
    title: 'Popover',
    category: 'ui-primitives',
    description: 'Popover overlay spacing and border treatment.',
    render: () => <PopoverHarness />,
  },
  {
    id: 'spinner',
    title: 'Spinner',
    category: 'ui-primitives',
    description: 'Spinner sizes and animation behavior.',
    render: () => <SpinnerHarness />,
  },
  {
    id: 'borrow-modal',
    title: 'Borrow Modal',
    category: 'modals',
    description: 'Real BorrowModal with deterministic market/position fixtures.',
    render: () => <BorrowModalHarness />,
    defaultCanvas: {
      maxW: 1200,
      pad: 24,
      bg: 'surface',
    },
  },
  {
    id: 'network-filter',
    title: 'Network Filter',
    category: 'filters',
    description: 'Real network selection dropdown component with compact/default variants.',
    render: () => <NetworkFilterHarness />,
  },
  {
    id: 'asset-filter',
    title: 'Asset Filter',
    category: 'filters',
    description: 'Token multi-select filter using realistic supported token fixtures.',
    render: () => <AssetFilterHarness />,
  },
  {
    id: 'account-identity',
    title: 'Account Identity',
    category: 'identity',
    description: 'Badge, compact, and full account identity variants.',
    render: () => <AccountIdentityHarness />,
  },
  {
    id: 'market-identity',
    title: 'Market Identity',
    category: 'identity',
    description: 'Market identity modes: focused, minimum, and badge.',
    render: () => <MarketIdentityHarness />,
  },
  {
    id: 'transaction-identity',
    title: 'Transaction Identity',
    category: 'identity',
    description: 'Explorer-linked transaction hash badges.',
    render: () => <TransactionIdentityHarness />,
  },
  {
    id: 'collateral-icons-display',
    title: 'Collateral Icons Display',
    category: 'identity',
    description: 'Overlapping collateral icons with overflow tooltip badge.',
    render: () => <CollateralIconsDisplayHarness />,
  },
  {
    id: 'section-tag',
    title: 'Section Tag',
    category: 'data-display',
    description: 'Bracketed section labels used in landing surfaces.',
    render: () => <SectionTagHarness />,
  },
  {
    id: 'market-selector',
    title: 'Market Selector',
    category: 'data-display',
    description: 'Single market row selector card used in selection flows.',
    render: () => <MarketSelectorHarness />,
  },
  {
    id: 'market-details-block',
    title: 'Market Details Block',
    category: 'data-display',
    description: 'Collapsible market details with supply/borrow preview states.',
    render: () => <MarketDetailsBlockHarness />,
  },
  {
    id: 'table-container-header',
    title: 'Table Container Header',
    category: 'data-display',
    description: 'Table container with title/actions and compact rows.',
    render: () => <TableContainerWithHeaderHarness />,
  },
  {
    id: 'table-pagination',
    title: 'Table Pagination',
    category: 'data-display',
    description: 'Pagination control with page jump and entry count.',
    render: () => <TablePaginationHarness />,
  },
  {
    id: 'icon-switch',
    title: 'Icon Switch',
    category: 'controls',
    description: 'Plain and icon-thumb switch states and sizes.',
    render: () => <IconSwitchHarness />,
  },
  {
    id: 'refetch-icon',
    title: 'Refetch Icon',
    category: 'controls',
    description: 'Smooth spinning reload icon behavior during fetch states.',
    render: () => <RefetchIconHarness />,
  },
  {
    id: 'dropdown-menu',
    title: 'Dropdown Menu',
    category: 'controls',
    description: 'Menu items, checkbox items, and radio groups.',
    render: () => <DropdownMenuHarness />,
  },
  {
    id: 'toast',
    title: 'Toast',
    category: 'controls',
    description: 'Styled success, error, and info toast triggers.',
    render: () => <ToastHarness />,
  },
  {
    id: 'market-selection-modal',
    title: 'Market Selection Modal',
    category: 'modals',
    description: 'Live market selection modal from the app workflow.',
    render: () => <MarketSelectionModalHarness />,
    defaultCanvas: {
      maxW: 1280,
      pad: 24,
      bg: 'surface',
    },
  },
  {
    id: 'supply-modal',
    title: 'Supply Modal',
    category: 'modals',
    description: 'Real SupplyModalV2 with deterministic market/position fixtures.',
    render: () => <SupplyModalHarness />,
    defaultCanvas: {
      maxW: 1200,
      pad: 24,
      bg: 'surface',
    },
  },
];

export const uiLabCategoryOrder = ['ui-primitives', 'filters', 'identity', 'data-display', 'controls', 'modals'] as const;

export const uiLabCategoryLabel: Record<(typeof uiLabCategoryOrder)[number], string> = {
  'ui-primitives': 'UI Primitives',
  filters: 'Filters & Selection',
  identity: 'Identity',
  'data-display': 'Data Display',
  controls: 'Controls',
  modals: 'Modals',
};
